### ISSUE TITLE
ValueError: num_samples should be a positive integeral value, but got num_samples=0

### ISSUE THREAD

**Issue by AbnerCSZ** [abdo-eldesokey/nconv#5]
Hi!
When I run:
```
 python3 run-nconv-cnn.py -mode eval -exp /home/chen/nconv/workspace/exp_guided_nconv_cnn_l1
```
This is a error:
```
Traceback (most recent call last):
  File "run-nconv-cnn.py", line 56, in <module>
    dataloaders, dataset_sizes = KittiDepthDataloader(params)
  File "/home/chen/nconv/dataloader/KittiDepthDataloader.py", line 44, in KittiDepthDataloader
    dataloaders['train'] = DataLoader(image_datasets['train'], shuffle=True, batch_size=params['train_batch_sz'], num_workers=4)
  File "/home/chen/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 802, in __init__
    sampler = RandomSampler(dataset)
  File "/home/chen/.local/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 64, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integeral value, but got num_samples=0
```
Could you tell me why?
Thanks!

**Comment by abdo-eldesokey** [comment]
Hi,
I think the error might be coming from giving an argument in the wrong way.
The argument -exp should take the name of the experiment directory inside workspace folder.
So please try to call instead:
```
 python3 run-nconv-cnn.py -mode eval -exp exp_guided_nconv_cnn_l1
```
Thank you.

**Comment by AbnerCSZ** [comment]
Thank you very much!
This is my result
```
{'train': {85898}, 'selval': {1000}, 'val': {6852}, 'test': {1000}}
< Evaluate mode ! >
=> Loading last checkpoint ... Checkpoint was loaded successfully!

Evaluating on [selval] set, Epoch [40] !

Evaluation results on [selval]:
=============================
[Loss]: 0.01568584
[MAE]: 0.20577325
[RMSE]: 0.90461409
[MRE]: 0.01125723
[Delta1]: 0.68974859
[Delta2]: 0.88703215
[Delta3]: 0.94724751
```
